services:
    nginx:
        container_name: nginx
        build:
            context: ./requirements/nginx/
            dockerfile: Dockerfile
        ports:
            - "443:443"
        env_file:
            - .env
        networks:
            - docker_network
        volumes:
            - wp_website:/var/www/html
        depends_on:
            - wordpress
        restart: always
    mariadb:
        container_name: mariadb
        build:
            context: ./requirements/mariadb/
            dockerfile: Dockerfile
        env_file:
            - .env
        networks:
           - docker_network
        restart: always
    wordpress:
        container_name: wordpress
        build:
            context: ./requirements/wordpress/
            dockerfile: Dockerfile
        depends_on:
            - mariadb
        env_file:
            - .env
        volumes:
            - wp_website:/var/www/html
        networks:
            - docker_network
        restart: always
networks:
    docker_network:
        driver: bridge
volumes:
  wp_website:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/fmoran-m/wp_website
