services:
    nginx:
        build:
            context: ./requirements/nginx/
            dockerfile: Dockerfile
        ports:
            - "443:443"
        restart: always
    mariadb:
        build:
            context: ./requirements/mariadb/
            dockerfile: Dockerfile
        ports:
            - "3306:3306"
        env_file:
            - .env
        restart: always
